In [1]:
import numpy as np

x = [1,2,3]
y = np.array(x)

print(y)
print(type(y))

[1 2 3]
<class 'numpy.ndarray'>


In [2]:
arr2 = np.array([[1,2,3],[1,2,3]])
print(arr2)

[[1 2 3]
 [1 2 3]]


In [3]:
l = []

for _ in range(1,3):
    arr = int(input("enter : "))
    l.append(arr)

print(l)

enter :  1
enter :  2


[1, 2]


In [10]:
arrn = np.array([1,2,3,4],[1,2,3,4],[1,2,3,4],ndmin=10)
print(arrn)
print(arrn.ndim)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given