# Zeros

In [3]:
import numpy as np

arr_zero = np.zeros(4)
arr_2d_zero = np.zeros((3,4))
print(arr_zero)
print()
print(arr_2d_zero)


[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones

In [4]:
import numpy as np

arr_one = np.ones(4)
arr_2d_one= np.ones((3,4))
print(arr_one)
print()
print(arr_2d_one)


[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Empty Array


In [8]:
arr_empt = np.empty(4)
print(arr_empt)

[1. 1. 1. 1.]


# Range

In [9]:
ranging = np.arange(5)
print(ranging)

[0 1 2 3 4]


# Digonal

In [10]:
arr_dig = np.eye(3)
print(arr_dig)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
arr_dig = np.eye(3,4)
print(arr_dig)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


# linspaces

In [18]:
space = np.linspace(1,10,num = 5)
space1 = np.linspace(0,20,num = 5)
print(space)
print(space1)

[ 1.    3.25  5.5   7.75 10.  ]
[ 0.  5. 10. 15. 20.]
