# Random

# rand()

In [2]:
import numpy as np

var = np.random.rand(4)
print(var)

[0.49375746 0.22867841 0.24675485 0.98184351]


In [3]:
var2 = np.random.rand(2,5)
print(var2)

[[0.26739104 0.65330328 0.07102816 0.8014305  0.87917812]
 [0.75475331 0.87178203 0.91976723 0.5924771  0.50188877]]


# Randn()

In [5]:
var3 = np.random.randn(6)
print(var3)

[ 1.2290682  -0.79266507  0.82402552 -1.23869517  1.46548694 -1.73135762]


# Ranf()

In [6]:
var4 = np.random.ranf(5)
print(var4)

[0.42923169 0.61524966 0.08026962 0.39392238 0.07833669]


# Randint()

In [8]:
var5 = np.random.randint(5,20,5)  # (min,max,total_elments)
print(var5)

[ 6  5 16  5  6]
