data type in python:
string
int
float
bool
complex

dat type in numpy :
- i for int
- b for bool
- u for unsigned
- f for float
- c for  complex float
- m for timedelta
- M for datetime
- O for object
- S for string
- U for unicode string
- V memory 

In [1]:


import numpy as np
arr = np.array([1,2,3,4])
print(arr.dtype)


int32


In [3]:
arr1 = np.array(["raj","rani","ram"])
print(arr1.dtype)

<U4


In [6]:
arr3 = np.array([1,2,3,4],dtype = 'S')
print(arr3)
print(arr3.dtype)


[b'1' b'2' b'3' b'4']
|S1


In [7]:
arr4 = np.array([1,2,3,4],dtype = 'i4')
print(arr4)
print(arr4.dtype)

[1 2 3 4]
int32


In [12]:
arr5 = np.array([1.1,2.2,3.3,4.4])
new_arr = arr5.astype('i')
new_arr1 = arr5.astype(int)
print(arr5)
print(arr5.dtype)
print(new_arr)
print(new_arr.dtype)
print(new_arr1)
print(new_arr1.dtype)

[1.1 2.2 3.3 4.4]
float64
[1 2 3 4]
int32
[1 2 3 4]
int32


In [15]:
arr5 = np.array([1,0,3,4])
new_arr = arr5.astype(bool)
new_arr1 = arr5.astype(int)
print(arr5)
print(arr5.dtype)
print(new_arr)
print(new_arr.dtype)


[1 0 3 4]
int32
[ True False  True  True]
bool
