# diffrence b/w numpy arra copy vs view

# make copy

In [4]:
import numpy as np
arr = np.array([1,2,3,4])
arr2 = arr.copy()
print(arr)
print(arr2)

[1 2 3 4]
[1 2 3 4]


In [6]:
arr = np.array([1,2,3,4,6])
arr2 = arr.copy()
arr[0] = 10
print(arr)
print(arr2)

[10  2  3  4  6]
[1 2 3 4 6]


# make view

In [5]:
arr = np.array([1,2,3,4])
arr2 = arr.view()
arr[0] = 10
print(arr)
print(arr2)

[10  2  3  4]
[10  2  3  4]
