# Reshaping :changing the shape of an array

# reshaping from 1D to 2D

In [9]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1 = arr.reshape(3,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# reshaping from 1D to 3D

In [21]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1 = arr.reshape(2,3,2)   # (indexing divide b 2, 3 list , in 3 list 2 elmnts)
print(arr1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [17]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1 = arr.reshape(2,3,2)   # (indexing divide b 2, 3 list , in 3 list 2 elmnts)
print(arr1.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# unknown dimention

In [25]:
arr = np.array([1,2,3,4,5,6,7,8])
arr1 = arr.reshape(2,2,-1)     # -1 is for unknown its calculate itself
print(arr1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# reshaping from 2D to 1D

In [26]:
arr = np.array([[1,2,3],[4,5,6]])
arr2 = arr.reshape(-1)
print(arr2)

[1 2 3 4 5 6]
