# joining the numpy array : concatinate

In [2]:
import numpy as np
arr = np.array([1,2,3])
arr2 = np.array([4,5,7])
arr3 = np.concatenate((arr,arr2))
print(arr3)

[1 2 3 4 5 7]


# joining 2D array

In [14]:
arr = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr3 = np.concatenate((arr,arr2),axis = 1)  # axis is means row means 0th is for 0th only
print(arr3)

[[1 2 5 6]
 [3 4 7 8]]


# joining using stack

In [12]:
arr = np.array([1,2,3])
arr2 = np.array([4,5,7])
arr3 = np.stack((arr,arr2), axis = 1)
print(arr3)

[[1 4]
 [2 5]
 [3 7]]


# stacking along with rows

In [4]:
arr = np.array([1,2,3])
arr2 = np.array([4,5,7])
arr3 = np.hstack((arr,arr2))
print(arr3)

[1 2 3 4 5 7]


# stacking along with columns

In [6]:
arr = np.array([1,2,3])
arr2 = np.array([4,5,7])
arr3 = np.vstack((arr,arr2))
print(arr3)

[[1 2 3]
 [4 5 7]]


# staking along with hight

In [7]:
arr = np.array([1,2,3])
arr2 = np.array([4,5,7])
arr3 = np.dstack((arr,arr2))
print(arr3)

[[[1 4]
  [2 5]
  [3 7]]]
