# search an array

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,4,4])

arr2 = np.where(arr == 4)
print(arr2)

(array([3, 5, 6], dtype=int64),)


# now we will find the indexes where the value are even and odd

In [5]:
arr = np.array([1,2,3,4,5,6,7,8])

arr2 = np.where(arr % 2 == 0)
arr3 = np.where(arr % 2 != 0)
print(arr2)
print(arr3)

(array([1, 3, 5, 7], dtype=int64),)
(array([0, 2, 4, 6], dtype=int64),)


# search sorted : perform bin search in array

In [9]:
arr = np.array([1,2,3,5,4,6,7,8])

arr2 = np.searchsorted(arr,4)

print(arr2)

3


In [12]:
arr = np.array([1,2,3,4,5,6,7,8])

arr2 = np.searchsorted(arr, 4, side = 'right')  # search from right

print(arr2)

4


# insert arr and find index of them

In [20]:
arr = np.array([1,3,5])

arr2 = np.searchsorted(arr,[2,4,6])

print(arr2)

[1 2 3]


In [21]:
arr = np.array([2,3,5])

arr2 = np.searchsorted(arr,[4,6])
print(arr2)

[2 3]
