# sort()

In [3]:
import numpy as np
arr = np.array([7,5,6,1,3,4,9])
print(np.sort(arr))   # like copy orginal array is no changes
print(arr)

[1 3 4 5 6 7 9]
[7 5 6 1 3 4 9]


# sort by string

In [5]:
string = np.array(['z','g','r','s'])
boolin = np.array(['True','False','False'])
print(np.sort(string))
print(np.sort(boolin))

['g' 'r' 's' 'z']
['False' 'False' 'True']


# for 2D array

In [9]:
arr = np.array([[3,5,4],[1,5,3]])
print(np.sort(arr))

[[3 4 5]
 [1 3 5]]
