In [ ]:
# Getting some elmt out of an existing array and 
# creating a new array is called filtering

In [2]:
import numpy as np
data = np.array([41,42,43,44])
data1 = [True,False,True,False]
final_data = data[data1]
print(final_data)  # false not taken

[41 43]


# Create Filter Array

In [6]:
emptydata = []
for num in data:
    if num > 42:
        emptydata.append(True)

    else:
        emptydata.append(False)

new_data = data[emptydata]
print(emptydata)
print(new_data)

[False, False, True, True]
[43 44]


# even elmnt

In [7]:
data = np.array([1,2,3,4,5,6,7])
emptydata = []

for num in data:
    if num % 2 == 0:
        emptydata.append(True)

    else:
        emptydata.append(False)

new_data = data[emptydata]

print(emptydata)
print(new_data)

[False, True, False, True, False, True, False]
[2 4 6]


# alternate mtd

In [8]:
emptydata = data > 2
new_data = data[emptydata]
print(emptydata)
print(new_data)

[False False  True  True  True  True  True]
[3 4 5 6 7]


In [9]:
emptydata = data  % 2 == 0
new_data = data[emptydata]
print(emptydata)
print(new_data)

[False  True False  True False  True False]
[2 4 6]
