# rand() randint() choice()

# Random : Not predictable

In [2]:
# import numpy as np
from numpy import random
data = random.randint(100)
print(data)

15


# Float num by rand()

In [12]:
from numpy import random
data = random.rand() # if not passing any to float rand it gives 0 to 1 num in float
print(data)

0.73210694173084


# genrate Random array

In [4]:
data = random.randint(100,size = (5))  # for 1D array
print(data)

[67 70 71 96 82]


In [7]:
# for 2D array
data = random.randint(100, size = (3,5))
print(data)

[[76 86 23 50  9]
 [66  4 53 18  4]
 [68 11 27 90 93]]


In [12]:
# for float 1D and 2D array
data1d = random.rand(5)
data2d = random.rand(3,5)
print(data1d)
print()
print(data2d)

[0.23933029 0.24447629 0.52008829 0.30464327 0.29162843]

[[0.68985384 0.73875167 0.2626508  0.95078617 0.59761281]
 [0.33246392 0.73601737 0.82417577 0.89263607 0.11593051]
 [0.16202138 0.32517062 0.82422551 0.49353423 0.08411803]]


# Choice

In [19]:
# 1D array
data = random.choice([3,5,7,9,1,4,6]) # randomly choose the num in this array
print(data)

5


In [30]:
# 2D array
data = random.choice([3,5,7,9,1,4,6],size = (3,5))
print(data)

[[3 6 5 1 7]
 [4 1 7 3 5]
 [4 4 6 7 9]]
