# NumPy Random Data Distribution

In [3]:
# data distribution is a list of all possible value and how often each value occor.

# such lists are important when working with statistics and data science.

# Random distribution: probability function.
# now we will generate 1-D with 100 values where each value has to be 3,5,7,9

# the probability for the value 3 is set to be 0.1
# the probability for the value 5 is set to be 0.3
# the probability for the value 7 is set to be 0.6 
# the probability for the value 9 is set to be 0.0
# the sum of all probability numbers should be '1'

In [8]:
from numpy import random
data = random.choice([3,5,7,9], p = [0.1,0.3,0.6,0.0], size = (50)) # p is Probability
print(data)

[7 5 7 5 7 7 5 7 7 7 7 7 5 7 7 7 7 5 7 3 7 7 3 3 7 7 7 7 7 7 5 5 5 7 5 7 7
 5 3 7 5 7 7 7 7 7 5 7 7 3]


In [11]:
# 2D array
from numpy import random
data = random.choice([3,5,7,9], p = [0.1,0.3,0.6,0.0], size = (3,5)) # p is Probability
print(data)

[[7 3 7 7 7]
 [7 7 5 5 3]
 [7 7 7 7 7]]
