# shuffle() and permutation() 

In [1]:
# Permutation : arrangement of elements like
# [3,2,1] is permutation of [1,2,3] , [2,1,3] and vice versa

# 2 methods

# 1) shuffle()  and 2) permutation()



# 1) shuffle()

In [7]:
from numpy import random as rm
import numpy as np

data = np.array([1,2,3,4,5])
rm.shuffle(data)   # it shuffles the original array
print(data)

[1 4 5 2 3]


In [13]:
data = np.array([1,2,3,4,5])
rm.permutation(data)  # it not change in orginal array 
print(data)

[1 2 3 4 5]


In [12]:
data = np.array([1,2,3,4,5])
print(rm.permutation(data)) # its just printing
print(data)

[1 5 3 2 4]
[1 2 3 4 5]
